### ISSUE TITLE
About this paper

### ISSUE THREAD

**Issue by leexk312** [xingsumq/Us-DeFake#1]
Hello,I'd like to read your paper but I can't find it. Please tell me how to find it? Looking forward for your reply.

**Comment by xingsumq** [comment]
Hi, I'm so glad you‘re interested in this work. The paper is now in the camera-ready stage. Once I'm done, I'll publish the paper on arXiv, and put the link to the paper together with the code in this repository. I can get back to you then and let you know.

**Comment by xingsumq** [comment]
> Hello,I'd like to read your paper but I can't find it. Please tell me how to find it? Looking forward for your reply.

Hi, I'm so glad you‘re interested in this work. The paper is now in the camera-ready stage. Once I'm done, I'll publish the paper on arXiv, and put the link to the paper together with the code in this repository. I can get back to you then and let you know.

**Comment by leexk312** [comment]
OK,Thanks for your reply!

**Comment by xingsumq** [comment]
> 

Hi, I've released the paper with code. Please find in this repository. Thanks for your comments.
